### ISSUE TITLE
Format code with elixir formatter

### ISSUE THREAD

**Issue by axelson** [mindok/contex#12]
Would a PR that formats the code with the elixir formatter be accepted/welcome? It would be make it much easier for those of us whose editor automatically formats the code to submit PR's. Otherwise I have to manually pull out just the changes required from a large diff like: https://github.com/mindok/contex/compare/master...axelson:spread-labels

**Comment by mindok** [comment]
Closed with commit 544fe5c3d7aeaf2aa84109ba0e3361919f3fd7d9

**Comment by axelson** [comment]
Great, thanks! :confetti_ball:
