### ISSUE TITLE
Allow specifying rotation of labels

### ISSUE THREAD

**Issue by axelson** [mindok/contex#13]
Currently for a bar chart the rotation of the labels cannot be preset and instead only kicks in after a hard-coded number of elements (IIRC), for longer label text this results in unreadable text.

![contex-screenshot](https://user-images.githubusercontent.com/9973/78047567-368d6e00-7314-11ea-884f-0817f32f6e34.png)

**Comment by mindok** [comment]
Thanks @srowley - PR merged.
