### ISSUE TITLE
Implement Line chart

### ISSUE THREAD

**Issue by WernerBuchert** [mindok/contex#16]
Hi,
thanks for this interesting nice library.
I am interested in line charts that I have rendered with D3.js so far. I wonder how difficult it is to program the Line Plot?

Is it on the agenda at the moment?

Best regards,
Werner.

**Comment by mindok** [comment]
Hi Werner,

Yes - it is on the agenda, and not too far away, time permitting. A lot of the preparatory refactoring has been done. It should be reasonably straightforward. There is some commented code in pointplot that covers most of it, but we need to expose and implement a few options like markers and line smoothing to do it properly.

Thanks for your interest!

**Comment by WernerBuchert** [comment]
Hi,
is that still on the agenda?

At the moment we use Point Plot's, but line charts would really be better.
I guess there have been certain attempts, haven't there?

[# defp get_svg_line...](https://github.com/mindok/contex/blob/0e64e41916a6183c0df7d5b451090f3f4b4dada9/lib/chart/pointplot.ex#L221) in pointplot.ex

Best regards and thanks for this library,
Werner.

**Comment by mindok** [comment]
Hi @WernerBuchert - yes, it is still on, and will be addressed next. I have set aside a couple of days next week to work through some of the roadmap items. I know it's been a while - the day job has got in the way a bit.
