### ISSUE TITLE
Values not showing on axis on point plot

### ISSUE THREAD

**Issue by monjohn** [mindok/contex#20]
Hey, great library!

I am having a problem, which is probably of my own making. The values are not showing on the axis for my point plot.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/563576/81574095-5a13f180-9373-11ea-8b4f-62a38b709c28.png">

Here is the code for my little example:

```Elixir
 def basic_plot(test_data) do
    plot_content =
      PointPlot.new(test_data)
      |> PointPlot.set_y_col_names(["Humidity", "Temperature"])

    Plot.new(900, 500, plot_content)
    |> Plot.plot_options(%{legend_setting: :legend_right})
    |> Plot.to_svg()
  end

  defp make_test_data(socket) do
    data =
      Wetter.HumidityReading.generate_sample_data()
      |> Enum.map(fn %{timestamp: timestamp, temperature: temp, humidity: humidity} ->
        [timestamp, humidity, temp]
      end)
      |> Dataset.new(["Time", "Humidity", "Temperature"])

    assign(socket, test_data: data)
  end
```

**Comment by srowley** [comment]
Is it this issue (tick label styling)?

https://github.com/mindok/contex/issues/6

**Comment by monjohn** [comment]
Yep! Adding that styling did the trick. Thanks.
