### ISSUE TITLE
Change formatting for y-axis in PointPlot

### ISSUE THREAD

**Issue by building39** [mindok/contex#23]
Hello,
I have a need to plot NIC traffic data over time. I have a prototype that's working, but I would like the Y axis to be read something like "MB/sec" instead of a raw numeric value. I'm probably just too thick-headed to see how to do this. Any suggestions?
![Screenshot from 2020-06-29 17-25-18](https://user-images.githubusercontent.com/875327/86057730-b8815600-ba2d-11ea-90ad-f6d7ef8a5779.png)

**Comment by mindok** [comment]
Good question - the BarChart has a "custom_category_formatter" option and the scale system allows for a custom formatter for the ticks (see scales.ex in the contex_samples project - /scales). It looks like I haven't wired it up for the point plots. I'll have a look a little later today.

**Comment by mindok** [comment]
Latest commit to master now has the ability to provide a custom formatter function to x & y axes in point plot. I have updated the contex-samples app to demonstrate this for the y-axis.

**Comment by building39** [comment]
Excellent! Thank you very much.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: mindok <notifications@github.com> Date: 6/30/20  03:36  (GMT-05:00) To: mindok/contex <contex@noreply.github.com> Cc: Michael <mmartin4242@gmail.com>, Author <author@noreply.github.com> Subject: Re: [mindok/contex] Plotting nic traffic data (#23) 
Latest commit to master now has the ability to provide a custom formatter function to x & y axes in point plot. I have updated the contex-samples app to demonstrate this for the y-axis.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mindok/contex/issues/23#issuecomment-651608205",
"url": "https://github.com/mindok/contex/issues/23#issuecomment-651608205",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mindok** [comment]
Implemented in master
