### ISSUE TITLE
Update readme to install latest version (0.3.0)

### ISSUE THREAD

**Issue by BigTom** [mindok/contex#30]
The current installation instructions have:
```
defp deps do
    [
        {:contex, "~> 0.1.0"}
    ]
end
```

Which means that lazy, slapdash people might simply cut'n'paste version `0.1.0` into their code and THEN SPEND HALF-A-DAY TRYING TO UNDERSTAND WHY IT WANTS BarPlot NOT BarChart !!!!!  ;-)

suggest they are updated to:
```
defp deps do
    [
        {:contex, "~> 0.3.0"}
    ]
end
```

**Comment by mindok** [comment]
Updated in master to 0.4.0
