### ISSUE TITLE
Allow setting of all options in streamlined Plot.new function

### ISSUE THREAD

**Issue by mindok** [mindok/contex#32]
The range of options that can be passed in Plot.new/5 is much more limited than what could be set creating the PlotContent manually. Extent to include at least more common options such as colour scheme.

**Comment by srowley** [comment]
As I recall you can pass any PlotContent option to Plot.new/5. E.g.,

```
Plot.new(dataset, BarChart, 300, 200, colour_palette: :pastel1)

```

**Comment by mindok** [comment]
Unfortunately it looks like they get ignored. I have a note in the roadmap to rationalise the option handling. If all the options are held as a keyword list rather than individual values in the struct, this streamlined API approach should be more reliable.

**Comment by srowley** [comment]
That's weird. You would think this test would fail:
```
    test "Sets orientation on BarChart" do
      plot =
        Dataset.new([{1, 2, 3, 4}, {4, 5, 6, 4}, {-3, -2, -1, 0}], ["aa", "bb", "cccc", "d"])
        |> Plot.new(BarChart, 150, 200, orientation: :horizontal)

      assert plot.plot_content.orientation == :horizontal
    end
```
It will be interesting see what's going on there.
