### ISSUE TITLE
BarChart: Allow more control over Value Axis

### ISSUE THREAD

**Issue by BigTom** [mindok/contex#33]
Hi, 

In my BarChart the vertical axis has a range 0-20, BarChart  generates ticks of 0, 2.5, 5, 7.5 ...
My data is integral (numbers of items)
How can I make the ticks integer values within the range e.g. 0,2,4,8 ...  ?

Excited by Contex but struggling a bit to make it do what I want.  Can I ask questions here or is there a better forum?

Thanks

Tom

**Comment by mindok** [comment]
Hi @BigTom - this is as good a place as any to ask a question. Elixir Forums would be fine too.

To answer your question, you can't at the moment. The only direct control over the value axis in the BarChart is to set the value range using `force_value_range\2`. It would be a reasonably straightforward thing to allow attaching manually created scales to the BarChart (and also PointPlot). https://contex-charts.org/scales shows some of the options (code here: https://github.com/mindok/contex-samples/blob/master/lib/contexsample_web/live/scales.ex).

I've set aside a day or two next week to make a few enhancements - what do you see as the most intuitive way to set the scale options explicitly? Something like:
```
BarChart.new(...)
 |> BarChart.value_scale(ContinuousLinearScale, min, max, interval_size)
```

or more explicit
```
scale =  ContinuousLinearScale.new()
      |> ContinuousLinearScale.domain(min, max)
      |> ContinuousLinearScale.interval_count(intervals)

BarChart.new(...)
  |> BarChart.attach_value_scale(scale)
```

or other? or both?

**Comment by BigTom** [comment]
Hi, I think the more explicit create and attach a scale works in my head.  Having said that, value_scale/4 would be a convenient  short cut to go with it.

Thanks

Tom

**Comment by mindok** [comment]
Note to self - update deprecation warning in `set_default_scales` to point to new way to override scales
