### ISSUE TITLE
What about missing/nil values?

### ISSUE THREAD

**Issue by WernerBuchert** [mindok/contex#37]
At the moment missing or nil values are not allowed, if I tested this correctly.
Is this quite difficult to implement or does this requirement throw everything out of whack?

We use Point Plot and btw. will test the new Line Chart's, thank you for the implementation!

Examples for the use of missing values are ApexCharts oder billboard.js Charts:
[ApexCharts missing values](https://apexcharts.com/javascript-chart-demos/line-charts/null-values/)

**Comment by mindok** [comment]
Hi @WernerBuchert,
It would be relatively easy to do in Point Plot - just a case expression in get_svg_point to check x & y aren't nil, before rendering the point.

For Line Plots it's a little more complicated - you have to make a call on whether to just pretend the missing point isn't there and connect the line between the points either side (this is the already implemented approach), draw a dashed line (or similar), or just break the line and start a new one - as per the ApexCharts link you sent. 

The current implementation can be found in LinkPlot.ex - search for `  |> Enum.filter(fn {x, y} -> not (is_nil(x) or is_nil(y)) end)`

The ApexCharts approach would be a little fiddly to implement with the various corner cases (single point line segments etc), but nothing too hard I don't think.

**Comment by WernerBuchert** [comment]
Thanks for the prompt reply and for your work.
I will try this out on the Point Plot Charts, that's enough for now. 
If I have time, I will have a look at the line charts.

**Comment by enilsen16** [comment]
@mindok similar to the question above, Is there a recommended approach for rendering an empty plot point or line plot? A plot with no data at all basically

**Comment by mindok** [comment]
Hi @enilsen16,

Good question. It should be ok if you provide a dataset with zero rows (e.g. `Dataset.new([], ["x", "y")`) and explicitly set the x & y scales using the `custom_x_scale` and `custom_y_scale` options.

**Comment by enilsen16** [comment]
> Hi @enilsen16,
> 
> Good question. It should be ok if you provide a dataset with zero rows (e.g. `Dataset.new([], ["x", "y")`) and explicitly set the x & y scales using the `custom_x_scale` and `custom_y_scale` options.

Yep this seems to work. Thank you!

**Comment by janwirth** [comment]
Would be nice to allow for interpolation of missing values and potentially render them differently.
