### ISSUE TITLE
Is there a way to define custom x-axis values for the TimeSeries scale?

### ISSUE THREAD

**Issue by enilsen16** [mindok/contex#39]
So if I understand correctly the best way to use custom scales for time series data, for example to change the default formatting of "%h %s" for a 1 second tick, I need to create a TimeSeries struct and pass in those values to the LinePlot? Same thing for the number of intervals right?

**Comment by mindok** [comment]
You can set a custom formatter function for the scale by setting either the `:custom_x_formatter` or `:custom_y_formatter` option when creating the plot. This should be an arity-1 function, e.g.:

```elixir
    defp format_my_tick(tick_value),
      do: NimbleStrftime.format(tick_value, "%d %b")

    chart = PointPlot.new(dataset, custom_x_formatter: &format_my_tick/1, ...)

```


If you want to control the intervals etc, then yes, you need to create a `TimeScale` and set the interval count. Note that it may not honour the interval count if it doesn't look `nice` - there's a comment against the nice function to explain.
