### ISSUE TITLE
Render as png

### ISSUE THREAD

**Issue by lud** [mindok/contex#43]
Hi, I have an elixir app and must display charts in Slack. But Slack does not support SVG. I know I can use inkscape as a command line tool, but it is a bit overkill. Do you know any other tool that I could use.

Also, your charts are dynamic, so I guess there is JS inside the graphs, they are not just images. Would it work, still ?

Thank you

**Comment by mindok** [comment]
You will need some way to convert SVG to a format Slack can display (eg PNG). I’m not aware of any Elixir libraries that can do that. Maybe rsvg-convert is lighter weight than Inkscape. 

The chart interactivity isn’t done with contained JavaScript - the updates are all done server side. you can easily intercept the generated SVG server-side before it is sent to the client. Actually, you don’t even need to send it to the client if you don’t need to.

**Comment by lud** [comment]
Thank you, I did a quick check with librsvg on a sample image and it seems to work well.

> you can easily intercept the generated SVG server-side before it is sent to the client. Actually, you don’t even need to send it to the client if you don’t need to.

Well there is no client actually! So I have no choice. 

Now I'll abuse my own issue to ask if you have support for stacked polylines/areas? And if not, how far would I be to code that?

Thank you

**Comment by mindok** [comment]
You could easily simulate a stacked poly line by pre-processing the dataset and using a line chart. A stacked area chart needs work to the code. It’s not too hard, just a bit fiddle to lay down the polygons isn’t the right sequence so they look nice. If you want to raise a separate issue for that I’ll be able to take a look soon - there are a few fixes and an outstanding PR merge I want to get to in the next week or so.

**Comment by lud** [comment]
Ok ! Thenk you, I'll do my best :)
