### ISSUE TITLE
Suggestion: support hyperlinks

### ISSUE THREAD

**Issue by nathanl** [mindok/contex#47]
It can be useful to have hyperlinks in charts. For example, in a system which runs jobs, you could graph the duration of the jobs and have each point be a link to that job's details. (I have a couple of use cases like that in mind.)

Apparently hyperlinks in inline SVG [can be done like this](https://alligator.io/svg/hyperlinks-svg/).

Maybe the best way to support that would be to pass a link function, which could look at the dataset and use one of the values (like `id:`) to build a link.

**Comment by mindok** [comment]
You can attach LiveView event handlers to `BarChart`s and `GanttChart` currently - this handles the use case. If we need event handlers for other chart types, we can add them
