### ISSUE TITLE
Ability to see Sparkline datapoint

### ISSUE THREAD

**Issue by edisonywh** [mindok/contex#5]
Right now it's dead simple to make a Sparkline chart, as it's just a list of values.

```elixir
data = [1, 2, 3, 4, 5, 6]
```

and this renders out a chart nicely, but then the chart would look something like:

![image](https://user-images.githubusercontent.com/20277437/74573742-c1dbbb80-4f81-11ea-9cdb-61a84d893aaa.png)

This doesn't really give off any context.

What I'd propose, I'm not sure if very feasible, but maybe something like:

```elixir
data = [{"monday", 123, {"tuesday", 42}]
```

A list of tuples, with the first element of the tuple being used as the value for when you hover over the point on the chart.

**Comment by mindok** [comment]
So I think we should handle this in PointPlot (or something similar, like LinePlot). There are a couple of issues doing it within the sparkline:
1. The sparkline is drawn using SVG lines - there is no ability to insert title elements for each point without overlaying points anyway.
2. Sparklines are designed to be embedded within their context - see https://en.wikipedia.org/wiki/Sparkline so I don't think it's appropriate to be adding more details.

I'm closing this for now, but will bump up priority on either adding lines to the PointPlot or introducing a new LinePlot, as I think that's where it should be done.
