### ISSUE TITLE
install version 0.4.0 don't match the version on Mix

### ISSUE THREAD

**Issue by romenigld** [mindok/contex#50]
I am trying to install the contex with the version `0.4.0`:

` {:contex, "~> 0.4.0"}`

And mix complains for this:
```
 mix deps.get
** (Mix) No matching version for contex ~> 0.4.0 (from: mix.exs) in registry

The latest version is: 0.3.0
❯ mix hex.info contex
Contex - a server-side charting library for Elixir.

Config: {:contex, "~> 0.3.0"}
Releases: 0.3.0, 0.2.0, 0.1.0

Licenses: MIT
Links:
  GitHub: https://github.com/mindok/contex
  Website: https://contex-charts.org/
```

But the initial README.md tells to install the version 0.4.0.

**Comment by mindok** [comment]
The readme is tied to the current development (for release 0.4.0) rather than what's currently in hex. 0.3.0 is the latest released version. I'll update the readme to match what's in hex.
