### ISSUE TITLE
Publish new Hex version

### ISSUE THREAD

**Issue by vanvoljg** [mindok/contex#53]
Hello!

I have a package that I'm trying to publish, but it requires some functions that are only available in your development version of ContEx. Unfortunately, Hex is telling me I'm unable to publish a package which depends on a git hash, and is requiring that I use a Hex-published version.

Is there any chance that a new version is coming any time soon?

Thank you!

**Comment by mindok** [comment]
Hi Jesse,

Yep - on it!

**Comment by mindok** [comment]
Done

**Comment by vanvoljg** [comment]
Greatly appreciated, thank you so much! :grinning:
