### ISSUE TITLE
SparkLine grid?

### ISSUE THREAD

**Issue by cedricPoncot** [mindok/contex#54]
Hi,
Is it possible to draw the grid behind the Sparkline plot?
i don't understand how to do it :/

Cédric

**Comment by cedricPoncot** [comment]
Or at least the axes ?

**Comment by mindok** [comment]
Hi @cedricPoncot - the sparkline is meant to be a super-simple representation with no axes or grid. If you want that you are better off making a `LinePlot`. There's a bit more setup, but you will get the control you need. However, there is currently no fill option on a line plot.

If you want to manually draw axes, you can generate the SVG for axes quite easily. Take a look at scales.ex (`ContexSampleWeb.ScalesLive`) in the sample application (https://github.com/mindok/contex-samples) to see how to do this. You could then combine the SVG output from the sparkline with the SVG output from the axis.

**Comment by cedricPoncot** [comment]
Hi, thx a lot  ! I'll manually draw axes :)
