### ISSUE TITLE
Labels have no color

### ISSUE THREAD

**Issue by edisonywh** [mindok/contex#6]
![image](https://user-images.githubusercontent.com/20277437/74575901-13d40f80-4f89-11ea-9739-8be98109529c.png)

As can see from the image above, the X and Y labels are clearly there (I also checked the DevTool and they are there indeed), but then they have on color. If I manually change the stroke of the `<g>` tag to `stroke="#000"` then it does show up as black.

![image](https://user-images.githubusercontent.com/20277437/74576010-7af1c400-4f89-11ea-8f28-cfaac6a1bae7.png)

If I manually change the `stroke` to this

![image](https://user-images.githubusercontent.com/20277437/74576076-bdb39c00-4f89-11ea-9972-a6eded2cb482.png)

Then the graph shows with color:

![image](https://user-images.githubusercontent.com/20277437/74576114-e176e200-4f89-11ea-8c39-66620e813922.png)

**Comment by edisonywh** [comment]
I think the problem lies somewhere in `contex/lib/chart/axis.ex#86`. That's the path that generates the bits of code I changed manually, if I add `stroke="#000"` there and recompile, I can see the values updated correctly.

![Uploading image.png…]()

**Comment by mindok** [comment]
What happens if you set the css classes for the ticks in your app's css, e.g.:
```css
/* Styling for tick line */
.exc-tick {
  stroke: grey;
}

/* Styling for tick text */
.exc-tick text {
  fill: grey;
  stroke: none;
}
```

There's a short explanation here:
https://hexdocs.pm/contex/Contex.html

**Comment by edisonywh** [comment]
Oh that works! Thanks, can consider this issue closed I suppose :)
