### ISSUE TITLE
SVG font is changed when transforming to PNG

### ISSUE THREAD

**Issue by silviaherguedas** [mindok/contex#67]
Hello,
How could I embed the font in the SVG and that when I convert it to PNG it doesn't transform all the text?

![Selección_004](https://user-images.githubusercontent.com/43692656/179692019-84015878-71ed-4e93-b1c8-8b0cd76a43e7.png)

**Comment by mindok** [comment]
It's a pain! How are you currently converting to PNG? The best way I found was to use a front-end SVG export library as that has access to the browser's style context. I used https://sharonchoong.github.io/svg-exportJS/index.html, and then use a download button calling a LiveView Hook. The hook code looks something like the following, with the `data-file` attribute set to the filename you want and `data-svg` set to the id of the SVG node:

```js
Hooks.SaveSvg = {
   mounted() {
      let svgElementId = this.el.dataset.svg;
      let filename = this.el.dataset.file;

      this.el.addEventListener('click', () => {
         console.log("Downloading: " + svgElementId + " to " + filename);
         topbar.show();
         requestAnimationFrame(() => {
            requestAnimationFrame(() => {
               svgExport.downloadSvg(
                  document.getElementById(svgElementId),
                  filename,
                  {useCSS: false}
               );
            });
         });
         topbar.hide();
      })
   }
}
```

If `Contex` isn't generating an id that you can access (sorry - I can't remember), you may need to adjust the hook code to get access to the right DOM element using some other means.

**Comment by silviaherguedas** [comment]
Thank you @mindok!
but I'm doing everything from the back-end.
I generate the svg with the Contex library, and then transform it to png with Mogrify, and what my function returns is the base64 of the image in png.
Which when I embed it in a template I see it differently.

`path_svg = "<svg>....</svg>"`
`Mogrify.open(path_svg)
|> Mogrify.format("png")
|> Mogrify.save(path: path_png)`
`content = File.read!(path_png) |> Base.encode64()`
`{:ok, content}`

**Comment by mindok** [comment]
I did a bit of reading last night on Mogrify/ImageMagick rendering of PNG from SVG. There are a lot of variables that are outside the control of Contex. For example, which renderer it delegates to affects style handling. There are typically 3 mentioned - InkScape, RSVG, MSVG which all have different behaviours. My suggestion would be to take the output from Contex and play around with settings in Mogrify, potentially manually editing the Contex output to try embedding styles etc. When you have something that works, if we need to update Contex to allow the required style embedding, we can make an update.

There is a lot of discussion of this topic in the D3.js forums as D3 is primarily SVG based and developers experience the same set of problems.

**Comment by silviaherguedas** [comment]
Thanks @mindok , we have finally solved it by using the Cairosvg library instead of Mogrify
