### ISSUE TITLE
Legend not appearing

### ISSUE THREAD

**Issue by tfwright** [mindok/contex#71]
Thanks for your work on this library. It looks like it could be very useful.

I tried creating a few charts and everything seems to be working as expected except for legends. I am calling this on every chart: 

`Contex.Plot.plot_options(%{legend_setting: :legend_bottom})`

but no legends appear.

I found this in the docs: https://github.com/mindok/contex#legends

> Legends are generated for scales. Currently legend generation is only supported for a CategoryColourScale

But one chart is a bar chart modeled on the sample code here: https://contex-charts.org/barcharts

Any idea what might be going on? It might be nice to raise or at least show a warning when a setting is being ignored, rather than silently failing to respect it.

**Comment by mindok** [comment]
`:legend_bottom` is currently only available from master. Just check your deps to see if you are pointing to GitHub. The samples project has an example of how it should look in mix.exs
