### ISSUE TITLE
Log scale

### ISSUE THREAD

**Issue by l3nz** [mindok/contex#79]
I need a log scale for a project, and it looks like it's very easy to implement based on Linear. As I have to write it anyway, would you be interested in a PR?

Feature-wise I was looking at something that would be similar to `log` and `symlog` in Matplotlib - https://stackoverflow.com/questions/3305865/what-is-the-difference-between-log-and-symlog

(I see that it it listed as `ContinuousLogScale` as "Under consideration". Does this mean it's already somewhere?)

**Comment by mindok** [comment]
Hi @l3nz - that would be great! There's been no work towards implementing it as yet. 

I took a look at the symlog option in the link you sent, and I think that makes sense - one of the questions I had when I saw the GitHub email on my phone last night was handling of <=0, but the matplotlib approach seems like a very sensible approach.

**Comment by l3nz** [comment]
I think that the Matplotlib approach makes sense because it is state-of-the-art, so it s a good starting point.

I have a question: I think that much of the code will be shared between Linear and Log. E.g. computing maximum and minimum  values.

I think it would make sense to refactor functions that are shared, and have them in one place only. Would you put them in one Helper file, or within Log, with a medium-term perspective of removing them from Linear in order to reference the shared ones?

**Comment by mindok** [comment]
Good question. I think it depends a bit on context. Utility type functions (e.g. extents) are probably best extracted out into a Utils/Helper module. There is a Utils module that has this class of function already. I note there is an ugly reference to `ContinousLInearScale.extents` in sparkline.ex, so that's a good hint that some refactoring is needed!

Similarly, formatting ticks with number display options probably makes sense to centralise. This is probably better in a number scale helper module. 

Let me know if you see any other areas of duplication that are worth extracting.

**Comment by l3nz** [comment]
I'd do this: I'll write one module that contains a submodule for helpers, so that for now it is a one-file patch, and we can easily move it out later and remove duplications elsewhere.

**Comment by l3nz** [comment]
FYI - I have a working log scale now, need to do some cleaning up and make ticks work more reasonably, but its' basically there. I used the options syntax instead of multiple mutating calls, that is more Elixir-y. I spotted a few small bugs in LinearScale and am fixing them i the shared code.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/1101849/224533487-3ccc84f9-8a26-4ea8-8064-205222001062.png">

I have a couple of questions though:

- When you create a scale, it needs a range. When you create a custom scale, most of the times yo will want an automatic range, but at the moment there is no way for a scale to receive an automatic range. Would you be okay with  an option `auto-range: (dataset)` so you don't have to do an explicit calculation?
- At the moment, the login in `nice()` basically decides the domain, interval, and decimals. It would be better IMHO to have an option to set the number of decimals, and if that is nil, then a decision is made. Or setting (say) interval width or count would readjust the other one.

**Comment by mindok** [comment]
Looks awesome!

Re your questions:
1. Yes - auto-range for a dataset would be a useful option. I have thought that myself from time-to-time! We would also need to pass in the field.
2. You can override the decimals choice determined by the `nice` code by providing a tick formatter function currently. Externalising explicit formatting decisions into the tick formatter is probably the right way to go, but I can see that setting the number of decimal points would be more intuitive to many users, so happy to do that.
