### ISSUE TITLE
Tests failing with elixir 1.14.3

### ISSUE THREAD

**Issue by l3nz** [mindok/contex#80]
It looks like tests fail on Elixir 1.14 because they changed the way dates are represented (?)

```
asdf local elixir 1.13.4-otp-25

mix test


Finished in 0.1 seconds (0.00s async, 0.1s sync)
6 doctests, 173 tests, 0 failures
```

But

```
asdf local elixir 1.14.3-otp-25

mix test

Finished in 0.1 seconds (0.00s async, 0.1s sync)
6 doctests, 173 tests, 5 failures

```

This happens because (the error is the same in all failing tests):

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/1101849/226097950-429443ee-7480-4d0f-b169-6ce56370394f.png">

**Comment by mindok** [comment]
Modified tests to use `NaiveDateTime.compare` - fixed in commit c06f795
