### ISSUE TITLE
Sparklines rendering outside their parent element.

### ISSUE THREAD

**Issue by jimsynz** [mindok/contex#9]
Hi.

I'm trying to build simple dashboard using liveview which displays the output from various sensors connected to my system.  I'm having trouble with the sparkline paths being outside the visible area of the svg element:

<img width="766" alt="Screen Shot 2020-03-07 at 21 21 37" src="https://user-images.githubusercontent.com/59449/76139963-7b7a0800-60ba-11ea-8b38-a0a96f438f18.png">

In the above screenshot I have allowed the following CSS properties to the svg element so that I can see what's happening:

```css
svg {
  border: 1px blue solid;
  overflow: visible;
}
```

I believe that this is being caused by the code attempting to rescale the chart based on the data.  In the power sensor data this makes sense (because these values are all positive integers).  But for the orientation data the values are a quaternion (so they're all between -1 and 1).  I've scaled the data manually so that they're between 0 and 2, however that hasn't fixed the problem.  When I pick up my device and move it around the paths actually move vertically up and down the screen.

If you have any suggestions I'd love to hear them.

**Comment by mindok** [comment]
I’ll take a look in the next 24hrs. The sparkline code was the earliest I wrote for charting and SVG generation and I learnt quite a few tricks in the meantime so it probably needs revisiting. 

What would your expected behaviour be for values going negative? Would you want the “x-axis” to shift down to the minimum value, or to stay on the zero-line?

**Comment by jimsynz** [comment]
@mindok I'm fine with adjusting the dataset so that all values are displayed as positive values.

**Comment by mindok** [comment]
ok - negative numbers aren't the problem, small numbers are... As a temporary fix you could multiply everything by some factor that takes the data into around a 0-100 range while I figure it out.

**Comment by mindok** [comment]
I've just pushed a commit that should fix this.

**Comment by jimsynz** [comment]
Thanks @mindok.
